// <auto-generated />
namespace Sistema_Pedidos_SmaXtec.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ValorTotal_Class_Pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValorTotal_Class_Pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201709141354060_ValorTotal_Class_Pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
